export const GET_INFO_WALLET:string = 'GET_INFO_WALLET';
export const GET_INFO_WALLET_SUCCESS:string = 'GET_INFO_WALLET_SUCCESS';
export const GET_INFO_WALLET_FAIL:string = 'GET_INFO_WALLET_FAIL';
export const GET_TRANS_DETAIL_WALLET:string = 'GET_TRANS_DETAIL_WALLET'
export const GET_TRANS_DETAIL_WALLET_SUCCESS:string = 'GET_TRANS_DETAIL_WALLET_SUCCESS'
export const GET_TRANS_DETAIL_WALLET_FAIL:string = 'GET_TRANS_DETAIL_WALLET_FAIL'
