export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const CONFIRM_TEL_ACCOUNT = "CONFIRM_TEL_ACCOUNT"
export const CONFIRM_TEL_ACCOUNT_SUCCESS = "CONFIRM_TEL_ACCOUNT_SUCCESS"
export const CONFIRM_TEL_ACCOUNT_FAIL = "CONFIRM_TEL_ACCOUNT_FAIL"