export const GET_SLIDER ="GET_SLIDER";
export const GET_SLIDER_SUCCESS = "GET_SLIDER_SUCCESS";
export const GET_SLIDER_FAIL = "GET_SLIDER_FAIL";

export const ADD_SLIDER = "ADD_SLIDER";
export const ADD_SLIDER_SUCCESS = "ADD_SLIDER_SUCCESS";
export const ADD_SLIDER_FAIL = "ADD_SLIDER_FAIL";