export const GET_SLIDER ="GET_SLIDER";
export const GET_SLIDER_SUCCESS = "GET_SLIDER_SUCCESS";
export const GET_SLIDER_FAIL = "GET_SLIDER_FAIL";

export const ADD_SLIDER = "ADD_SLIDER";
export const ADD_SLIDER_SUCCESS = "ADD_SLIDER_SUCCESS";
export const ADD_SLIDER_FAIL = "ADD_SLIDER_FAIL";

export const REMOVE_SLIDER = "REMOVE_SLIDER";
export const REMOVE_SLIDER_SUCCESS = "REMOVE_SLIDER_SUCCESS";
export const REMOVE_SLIDER_FAIL = "REMOVE_SLIDER_FAIL";

export const EDIT_SLIDER = "EDIT_SLIDER";
export const EDIT_SLIDER_FAIL = "EDIT_SLIDER_FAIL";
export const EDIT_SLIDER_SUCCESS = "EDIT_SLIDER_SUCCESS";